//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UralAjans3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUs
    {
        public int MessageID { get; set; }
        public string SenderName { get; set; }
        public string CompanyName { get; set; }
        public string Message { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
